// <auto-generated />
using System;
using System.Collections.Generic;
using HumanResources.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResources.EntityFramework.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HumanResources.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("PersonalInformation", "HumanResources.Models.Employee.PersonalInformation#PersonalInformation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BirthDate")
                                .HasMaxLength(50)
                                .HasColumnType("INTEGER")
                                .HasColumnName("BirthDate");

                            b1.Property<string>("MaritalStatus")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MaritalStatus");

                            b1.Property<string>("NationalIdentificationNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("NationalIdentificationNumber");

                            b1.ComplexProperty<Dictionary<string, object>>("ContactInformation", "HumanResources.Models.Employee.PersonalInformation#PersonalInformation.ContactInformation#ContactInformation", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("EmailAddress")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("EmailAddress");

                                    b2.Property<string>("PhoneNumber")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PhoneNumber");

                                    b2.ComplexProperty<Dictionary<string, object>>("HomeAddress", "HumanResources.Models.Employee.PersonalInformation#PersonalInformation.ContactInformation#ContactInformation.HomeAddress#Address", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("City")
                                                .IsRequired()
                                                .HasMaxLength(50)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("City");

                                            b3.Property<string>("State")
                                                .IsRequired()
                                                .HasMaxLength(50)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("State");

                                            b3.Property<string>("Street")
                                                .IsRequired()
                                                .HasMaxLength(50)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("Street");

                                            b3.Property<string>("ZipCode")
                                                .IsRequired()
                                                .HasMaxLength(10)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("ZipCode");
                                        });
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Name", "HumanResources.Models.Employee.PersonalInformation#PersonalInformation.Name#PersonName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FirstName");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("LastName");

                                    b2.Property<string>("MiddleName")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MiddleName");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
